import { Router, Response } from 'express';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { db } from '../db/index.js';
import { env } from '../config/env.js';
import { validateRequest } from '../middleware/validate.js';
import { authenticateToken, optionalAuthenticateToken, AuthRequest } from '../middleware/auth.js';
import { rateLimit } from '../middleware/rateLimit.js';
import { randomUUID } from 'crypto';
import { getAddress, verifyMessage } from 'ethers';
import { clearSessionCookie, setSessionCookie } from '../auth/sessionCookie.js';

const router = Router();

const walletChallenges = new Map<string, { nonce: string; message: string; expiresAt: number }>();
const WALLET_CHALLENGE_TTL_MS = 5 * 60_000;

const walletAddressSchema = z.string().transform((value, ctx) => {
  try {
    return getAddress(value);
  } catch {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'A valid EVM wallet address is required' });
    return z.NEVER;
  }
});
const localWalletIdentifierSchema = z.coerce.string().trim().min(1, 'A local wallet identifier is required').max(100);

const issueToken = (user: (typeof db.users)[number], rememberMe = false) => jwt.sign(
  { id: user.id, seed_id: user.seed_id, role: user.role },
  env.JWT_SECRET,
  { expiresIn: rememberMe ? '7d' : '24h' }
);

const findOrCreateWalletUser = async (address: string): Promise<(typeof db.users)[number]> => {
  const normalized = address.toLowerCase();
  const seedId = `wallet:${normalized}`;

  return await db.findOrCreateUserDurable({
    seed_id: seedId,
    display_name: `Traveler ${address.slice(0, 6)}…${address.slice(-4)}`,
    email: `${normalized.slice(2)}@wallet.juanderquest.local`,
    avatar_url: `https://api.dicebear.com/7.x/identicon/svg?seed=${encodeURIComponent(normalized)}`,
    role: 'user',
    demo_points: 100,
    mjdq_balance: 100000,
    jdq_governance_balance: 15,
    scout_reputation: 250,
    is_public: false,
    handle: null,
    bio: null,
    status_text: null,
  });
};

router.get('/auth/wallet/config', (_req, res) => res.status(200).json({
  success: true,
  data: { mode: env.WALLET_AUTH_MODE, guest_login_enabled: env.GUEST_LOGIN_ENABLED },
}));

// Guest identity is generated by the server, never derived from a supplied wallet,
// username or seed. The session cookie is its only recovery credential.
router.post('/auth/guest-login',
  rateLimit({ policyId: 'auth:guest-login', windowMs: 60_000, max: 5 }),
  validateRequest(z.object({ body: z.object({ remember_me: z.boolean().optional() }).strict() })),
  optionalAuthenticateToken,
  async (req: AuthRequest, res: Response) => {
    res.setHeader('Cache-Control', 'private, no-store');
    if (!env.GUEST_LOGIN_ENABLED) return res.status(403).json({ success: false, error: { code: 'GUEST_LOGIN_DISABLED', message: 'Guest sign-in is unavailable.' } });
    try {
      if (env.NODE_ENV === 'production' && !db.usersRepo.getPool()) throw new Error('Durable storage required');
      let user;
      if (req.user) {
        user = db.usersRepo.getPool() ? await db.usersRepo.findById(req.user.id) : db.findUserById(req.user.id);
        if (!user || user.seed_id !== req.user.seed_id) return res.status(401).json({ success: false, error: { code: 'UNAUTHORIZED', message: 'Session account no longer exists.' } });
        if (!user.seed_id.startsWith('guest:') || user.role !== 'user') return res.status(409).json({ success: false, error: { code: 'SESSION_EXISTS', message: 'Sign out before starting a guest account.' } });
      } else {
        const identity = randomUUID();
        user = await db.findOrCreateUserDurable({
          seed_id: `guest:${identity}`, display_name: `Guest ${identity.slice(0, 8)}`,
          email: `${identity}@guest.invalid`, role: 'user', is_public: false,
          demo_points: 0, mjdq_balance: 0, jdq_governance_balance: 0, scout_reputation: 0,
        });
      }
      const remember = req.body.remember_me !== false;
      const token = issueToken(user, remember);
      setSessionCookie(res, token, remember);
      return res.json({ success: true, data: { user, auth_method: 'guest' } });
    } catch {
      return res.status(503).json({ success: false, error: { code: 'STORAGE_UNAVAILABLE', message: 'Guest account storage is unavailable. Please try again.' } });
    }
  });

router.post(
  '/auth/wallet/challenge',
  rateLimit({ policyId: 'auth:wallet-challenge', windowMs: 60_000, max: 20 }),
  validateRequest(z.object({ body: z.object({ address: walletAddressSchema }) })),
  (req, res) => {
    if (env.WALLET_AUTH_MODE !== 'signature') {
      return res.status(409).json({
        success: false,
        error: { code: 'AUTH_MODE_MISMATCH', message: 'Wallet signatures are disabled in local auth mode.' },
      });
    }
    const address = getAddress(req.body.address);
    const nonce = randomUUID();
    const message = [
      'Sign in to JuanDerQuest',
      '',
      `Wallet: ${address}`,
      `Nonce: ${nonce}`,
      'This request does not trigger a blockchain transaction or cost gas.',
    ].join('\n');
    walletChallenges.set(address.toLowerCase(), { nonce, message, expiresAt: Date.now() + WALLET_CHALLENGE_TTL_MS });
    return res.status(200).json({ success: true, data: { message, expires_in_seconds: 300 } });
  }
);

router.post(
  '/auth/wallet/login',
  rateLimit({ policyId: 'auth:wallet-login', windowMs: 60_000, max: 20 }),
  validateRequest(z.object({ body: z.object({ address: walletAddressSchema, signature: z.string().min(1), remember_me: z.boolean().optional() }) })),
  async (req, res) => {
    if (env.WALLET_AUTH_MODE !== 'signature') {
      return res.status(409).json({
        success: false,
        error: { code: 'AUTH_MODE_MISMATCH', message: 'Use the local wallet bypass in local auth mode.' },
      });
    }
    const address = getAddress(req.body.address);
    const key = address.toLowerCase();
    const challenge = walletChallenges.get(key);
    walletChallenges.delete(key);
    if (!challenge || challenge.expiresAt <= Date.now()) {
      return res.status(401).json({
        success: false,
        error: { code: 'INVALID_CHALLENGE', message: 'Wallet challenge is missing, expired, or already used.' },
      });
    }
    try {
      const recovered = getAddress(verifyMessage(challenge.message, req.body.signature));
      if (recovered !== address) throw new Error('Address mismatch');
    } catch {
      return res.status(401).json({
        success: false,
        error: { code: 'INVALID_SIGNATURE', message: 'The wallet signature could not be verified.' },
      });
    }
    try {
      const user = await findOrCreateWalletUser(address);
      const token = issueToken(user, req.body.remember_me === true);
      setSessionCookie(res, token, req.body.remember_me === true);
      return res.status(200).json({ success: true, data: { token, user, wallet_address: address } });
    } catch (err) {
      console.error('[auth] durable user creation failed in wallet login:', err);
      return res.status(503).json({
        success: false,
        error: { code: 'STORAGE_UNAVAILABLE', message: 'Durable user storage is unavailable. Please try again later.' },
      });
    }
  }
);

router.post(
  '/auth/wallet/local-login',
  rateLimit({ policyId: 'auth:wallet-local-login', windowMs: 60_000, max: 20 }),
  validateRequest(z.object({ body: z.object({ address: localWalletIdentifierSchema, remember_me: z.boolean().optional() }) })),
  async (req, res) => {
    if (
      env.NODE_ENV === 'production' ||
      env.WALLET_AUTH_MODE !== 'local' ||
      (env.NODE_ENV !== 'test' && !env.ALLOW_INSECURE_LOCAL_WALLET_AUTH)
    ) {
      return res.status(403).json({
        success: false,
        error: { code: 'LOCAL_AUTH_DISABLED', message: 'Local wallet bypass is disabled.' },
      });
    }
    const address = String(req.body.address).trim();
    try {
      const user = await findOrCreateWalletUser(address);
      const token = issueToken(user, req.body.remember_me === true);
      setSessionCookie(res, token, req.body.remember_me === true);
      return res.status(200).json({
        success: true,
        data: { token, user, wallet_address: address, auth_method: 'local_bypass' },
      });
    } catch (err) {
      console.error('[auth] durable user creation failed in local wallet login:', err);
      return res.status(503).json({
        success: false,
        error: { code: 'STORAGE_UNAVAILABLE', message: 'Durable user storage is unavailable. Please try again later.' },
      });
    }
  }
);

const loginSchema = z.object({
  body: z.object({
    seed_id: z.string().trim().min(1).max(100),
  }),
});

router.post('/auth/demo-login', rateLimit({ policyId: 'auth:demo-login', windowMs: 60_000, max: 20 }), validateRequest(loginSchema), async (req, res) => {
  if (!env.ALLOW_DEMO_LOGIN || env.NODE_ENV === 'production') {
    return res.status(403).json({
      success: false,
      error: {
        code: 'DEMO_LOGIN_DISABLED',
        message: 'Demo login is disabled for this environment.',
      },
    });
  }

  const { seed_id } = req.body;
  let user;
  try {
    // Never issue a JWT for a process-local seed when protected routes read
    // identities from PostgreSQL. A missing durable seed is not a login.
    user = db.usersRepo.getPool()
      ? await db.findUserBySeedDurable(seed_id)
      : db.findUserBySeed(seed_id);
  } catch {
    return res.status(503).json({ success: false, error: {
      code: 'STORAGE_UNAVAILABLE', message: 'Durable user storage is unavailable. Please try again later.',
    } });
  }

  if (!user) {
    return res.status(404).json({
      success: false,
      error: {
        code: 'NOT_FOUND',
        message: `Seed user with ID '${seed_id}' not found.`,
      },
    });
  }

  const token = jwt.sign(
    {
      id: user.id,
      seed_id: user.seed_id,
      role: user.role,
    },
    env.JWT_SECRET,
    { expiresIn: '24h' }
  );
  setSessionCookie(res, token, false);

  return res.status(200).json({
    success: true,
    data: {
      token,
      user,
    },
  });
});

const simulatedWalletLoginSchema = z.object({
  body: z.object({
    username: z.string().min(2, 'Username must be at least 2 characters'),
    password: z.string().min(2, 'Password must be at least 2 characters'),
  }),
});

router.post('/auth/simulated-wallet-login', validateRequest(simulatedWalletLoginSchema), async (req, res) => {
  if (env.NODE_ENV === 'production' || (env.NODE_ENV !== 'test' && !env.ALLOW_INSECURE_LOCAL_WALLET_AUTH)) return res.status(403).json({ success: false, error: { code: 'SIMULATED_LOGIN_DISABLED', message: 'Simulated wallet login is disabled for this environment.' } });
  const { username } = req.body;
  const cleanUsername = username.trim();
  const seedId = `user-${cleanUsername.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;

  let user = await db.findUserBySeedDurable(seedId);
  if (!user) {
    user = db.users.find(
      (u) =>
        u.display_name.toLowerCase() === cleanUsername.toLowerCase() ||
        u.seed_id.toLowerCase() === cleanUsername.toLowerCase()
    );
  }

  if (!user) {
    try {
      user = await db.findOrCreateUserDurable({
        seed_id: seedId,
        display_name: cleanUsername,
        email: `${cleanUsername.toLowerCase().replace(/[^a-z0-9]/g, '')}@juanderquest.local`,
        avatar_url: `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(cleanUsername)}`,
        role: 'user',
        demo_points: 100,
        mjdq_balance: 100000,
        jdq_governance_balance: 15,
        scout_reputation: 250,
        is_public: false,
        handle: null,
        bio: null,
        status_text: null,
      });

      db.ledger.push({
        id: `ledg_welcome_${Date.now()}`,
        user_id: user.id,
        entry_type: 'poa_reward',
        mjdq_delta: 100000,
        jdq_delta: 15,
        burned_mjdq: 0,
        description: 'MetaMask Starter Pack: 100,000 mJDQ + 15 JDQ + 250 Scout Rep',
        created_at: new Date().toISOString(),
      });
    } catch (err) {
      console.error('[auth] durable user creation failed in simulated login:', err);
      return res.status(503).json({
        success: false,
        error: { code: 'STORAGE_UNAVAILABLE', message: 'Durable user storage is unavailable. Please try again later.' },
      });
    }
  }

  const token = jwt.sign(
    {
      id: user.id,
      seed_id: user.seed_id,
      role: user.role,
    },
    env.JWT_SECRET,
    { expiresIn: '24h' }
  );
  setSessionCookie(res, token, false);

  const simulatedAddress = `0x${Array.from({ length: 40 }, () => Math.floor(Math.random() * 16).toString(16)).join('')}`;

  return res.status(200).json({
    success: true,
    data: {
      token,
      user,
      simulated_wallet_address: simulatedAddress,
      message: 'Simulated MetaMask Wallet Connected Successfully! Starter Demo Pack Credited.',
    },
  });
});

router.post('/auth/session/upgrade', authenticateToken, async (req: AuthRequest, res: Response) => {
  if (!req.headers.authorization) return res.status(400).json({ success: false, error: { code: 'BEARER_REQUIRED', message: 'A legacy bearer session is required.' } });
  try {
    const user = db.usersRepo.getPool() ? await db.usersRepo.findById(req.user!.id) : db.findUserById(req.user!.id);
    if (!user) return res.status(401).json({ success: false, error: { code: 'UNAUTHORIZED', message: 'Session account no longer exists.' } });
    const rememberMe = req.body?.remember_me === true;
    setSessionCookie(res, issueToken(user, rememberMe), rememberMe);
    return res.json({ success: true, data: user });
  } catch {
    return res.status(503).json({ success: false, error: { code: 'DATABASE_OUTAGE', message: 'Session could not be upgraded.' } });
  }
});

router.post('/auth/logout', (_req, res) => {
  clearSessionCookie(res);
  return res.json({ success: true });
});

router.get('/auth/me', authenticateToken, async (req: AuthRequest, res: Response) => {
  const userId = req.user?.id;
  let user;
  try { user = db.usersRepo.getPool() ? await db.usersRepo.findById(userId!) : db.findUserById(userId!); }
  catch { return res.status(503).json({ success: false, error: { code: 'DATABASE_OUTAGE', message: 'Session could not be validated.' } }); }

  if (!user) {
    clearSessionCookie(res);
    return res.status(401).json({
      success: false,
      error: {
        code: 'UNAUTHORIZED',
        message: 'Session account no longer exists.',
      },
    });
  }

  res.setHeader('Cache-Control', 'private, no-store');
  return res.status(200).json({
    success: true,
    data: user,
  });
});

export default router;
