-- Migration 025: Seed Pangasinan Discovery Spots for Infinite Scroll Demo
-- Enriches the provincial spot catalog with 36 authentic Pangasinan destinations
-- across Western, Central, and Eastern districts for smooth, multi-page infinite scroll demo.

INSERT INTO spots (
  id, slug, name, description, category, subcategory, tags,
  municipality, address, gps_lat, gps_lng, price_level, hours,
  amenities, image_url, source_type, source_name, source_url,
  trust_level, status, crowd_capacity_band, is_test, created_at, updated_at
) VALUES
(
  'spot-san-fabian-beach',
  'san-fabian-beach-promenade',
  'San Fabian Beach & Promenade',
  'A classic coastal getaway along Lingayen Gulf famous for gentle surf, beachfront cottages, seafood grilling huts, and panoramic views of the Benguet mountain backdrop.',
  'nature_outdoors',
  'beach',
  '["beach", "sunset", "coast", "family", "swimming"]'::jsonb,
  'San Fabian',
  'Barangay Nibaliw West, San Fabian, Pangasinan',
  16.1215,
  120.4045,
  1,
  '{"daily": "05:30-19:00"}'::jsonb,
  '["parking", "restrooms", "cottage_rentals", "lifeguard", "food_stalls", "scenic_view"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/places/san-fabian-beach/',
  'editorial',
  'published',
  'high',
  FALSE,
  NOW() - INTERVAL '12 days',
  NOW()
),
(
  'spot-agno-umbrella-rocks',
  'agno-umbrella-rocks',
  'Agno Umbrella Rocks',
  'Spectacular mushroom-shaped coral limestone formations sculpted over centuries by the pounding waves of the West Philippine Sea along the pristine Sabangan Beach.',
  'nature_outdoors',
  'rock_formation',
  '["rock_formations", "coast", "scenic", "hidden_gem", "photography"]'::jsonb,
  'Agno',
  'Sabangan Beach, Agno, Pangasinan',
  16.1189,
  119.7997,
  0,
  '{"daily": "06:00-18:00"}'::jsonb,
  '["parking", "viewing_deck", "photo_spot", "tidal_walks"]'::jsonb,
  'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/places/umbrella-rocks/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '11 days',
  NOW()
),
(
  'spot-balingasay-river',
  'balingasay-river-cruise',
  'Balingasay River Cruise & Mangroves',
  'Awarded as the cleanest inland body of water in Region 1, offering serene bamboo raft cruises through century-old mangrove sanctuaries, nipa canopies, and birdwatching trails.',
  'nature_outdoors',
  'river',
  '["river", "nature", "eco_tour", "mangroves", "birdwatching"]'::jsonb,
  'Bolinao',
  'Balingasay, Bolinao, Pangasinan',
  16.3533,
  119.8589,
  2,
  '{"daily": "08:00-17:00"}'::jsonb,
  '["parking", "boat_rental", "bamboo_raft", "restrooms", "eco_guide"]'::jsonb,
  'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
  'lgu',
  'Bolinao Tourism Office',
  'https://seepangasinan.com/places/balingasay-river/',
  'lgu_verified',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '10 days',
  NOW()
),
(
  'spot-surip-beach',
  'surip-beach-reef',
  'Surip Beach & Diving Reef',
  'A rugged limestone coast in Bani known for offshore coral reefs, underwater caverns, and deep sapphire waters popular with scuba divers, freedivers, and sunset campers.',
  'nature_outdoors',
  'beach',
  '["beach", "diving", "snorkeling", "rock_formations", "adventure"]'::jsonb,
  'Bani',
  'Surip, Bani, Pangasinan',
  16.2231,
  119.8542,
  1,
  '{"daily": "06:00-18:30"}'::jsonb,
  '["parking", "cottages", "scuba_gear", "snorkeling", "camping_ground"]'::jsonb,
  'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/places/surip-beach/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '10 days',
  NOW()
),
(
  'spot-death-pool-cabongaoan',
  'death-pool-cabongaoan',
  'Death Pool of Cabongaoan',
  'A natural swirling tide pool hollowed out of limestone bedrock along Burgos coast where ocean swells wash over jagged volcanic rocks into a crystal clear swimming basin.',
  'nature_outdoors',
  'tidal_pool',
  '["tidal_pools", "coast", "adventure", "swimming", "photography"]'::jsonb,
  'Burgos',
  'Cabongaoan Beach, Burgos, Pangasinan',
  15.9866,
  119.7611,
  0,
  '{"daily": "06:30-17:30"}'::jsonb,
  '["cottage_rentals", "rock_scramble", "photo_spot", "tidal_guide"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/places/cabongaoan-death-pool/',
  'editorial',
  'published',
  'medium',
  FALSE,
  NOW() - INTERVAL '9 days',
  NOW()
),
(
  'spot-bolinao-falls-2',
  'bolinao-falls-2',
  'Bolinao Falls 2',
  'The wider and calmer companion to Bolinao Falls 1, featuring natural limestone terraces, a turquoise plunge pool, and bamboo diving platforms shaded by wild banyan trees.',
  'nature_outdoors',
  'waterfall',
  '["waterfall", "nature", "freshwater", "swimming", "family"]'::jsonb,
  'Bolinao',
  'Samang Norte, Bolinao, Pangasinan',
  16.3089,
  119.8647,
  1,
  '{"daily": "07:00-17:00"}'::jsonb,
  '["parking", "restrooms", "cottages", "life_vest_rental", "swimming_pool"]'::jsonb,
  'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80',
  'lgu',
  'Bolinao Tourism Office',
  'https://seepangasinan.com/places/bolinao-falls-2/',
  'lgu_verified',
  'published',
  'medium',
  FALSE,
  NOW() - INTERVAL '9 days',
  NOW()
),
(
  'spot-bued-mangrove-park',
  'bued-mangrove-eco-park',
  'Bued Mangrove Eco-Park',
  'A community-managed coastal biosphere in Alaminos City featuring a kilometer-long bamboo boardwalk canopy, mangrove nursery, crab farming exhibits, and sunset watchtower.',
  'nature_outdoors',
  'park',
  '["mangroves", "nature", "eco_park", "boardwalk", "birdwatching"]'::jsonb,
  'Alaminos City',
  'Barangay Bued, Alaminos City, Pangasinan',
  16.1950,
  119.9917,
  1,
  '{"daily": "06:00-18:00"}'::jsonb,
  '["parking", "bamboo_walkway", "watchtower", "restrooms", "eco_briefing"]'::jsonb,
  'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
  'lgu',
  'Alaminos City Tourism',
  'https://www.alaminoscity.gov.ph/',
  'lgu_verified',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '8 days',
  NOW()
),
(
  'spot-busay-falls',
  'busay-falls-bani',
  'Busay Falls & Forest Reserve',
  'A secluded multi-tiered jungle cascade tucked into the foothills of Bani, featuring cold mountain runoff, mossy rock chutes, and shaded picnic boulders.',
  'nature_outdoors',
  'waterfall',
  '["waterfall", "nature", "hidden_gem", "hiking", "freshwater"]'::jsonb,
  'Bani',
  'Dacap Sur, Bani, Pangasinan',
  16.1689,
  119.8789,
  1,
  '{"daily": "07:30-16:30"}'::jsonb,
  '["parking", "nature_trail", "guide", "picnic_area"]'::jsonb,
  'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/places/busay-falls/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '8 days',
  NOW()
),
(
  'spot-cacupangan-cave',
  'cacupangan-cave-mabini',
  'Cacupangan Cave & Underground River',
  'An underground limestone wonderland in Mabini with crystalline stalactite chambers, subterranean streams, and adventurous spelunking passages guided by local conservationists.',
  'nature_outdoors',
  'cave',
  '["cave", "spelunking", "adventure", "nature", "underground_river"]'::jsonb,
  'Mabini',
  'Barangay Tagudin, Mabini, Pangasinan',
  16.0694,
  119.9403,
  1,
  '{"daily": "07:00-16:00"}'::jsonb,
  '["helmet_rental", "spelunking_guide", "parking", "registration_center"]'::jsonb,
  'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/places/cacupangan-cave/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '7 days',
  NOW()
),
(
  'spot-pinsal-falls',
  'pinsal-falls-san-quintin',
  'Pinsal Falls & Eco-Trail',
  'A roaring mountain waterfall located at the edge of the Caraballo Mountain range in San Quintin, celebrated for its crystal cold reservoir and lush mountain fern forest.',
  'nature_outdoors',
  'waterfall',
  '["waterfall", "nature", "mountains", "trekking", "swimming"]'::jsonb,
  'San Quintin',
  'Barangay Cabangaran, San Quintin, Pangasinan',
  15.9833,
  120.8167,
  0,
  '{"daily": "06:00-17:00"}'::jsonb,
  '["trailhead", "parking", "picnic_area", "freshwater_lagoon"]'::jsonb,
  'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Province of Pangasinan',
  'https://www.pangasinan.gov.ph/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '7 days',
  NOW()
),
(
  'spot-antong-falls',
  'antong-falls-sison',
  'Antong Falls & Mountain Brook',
  'A series of tranquil natural granite cascades and freshwater pools in the highlands of Sison, serving as a cool respite along the Bued River basin near the Benguet border.',
  'nature_outdoors',
  'waterfall',
  '["waterfall", "hiking", "nature", "cool_breeze", "mountains"]'::jsonb,
  'Sison',
  'Barangay Camangaan, Sison, Pangasinan',
  16.1733,
  120.5100,
  0,
  '{"daily": "06:00-17:00"}'::jsonb,
  '["footpath", "parking", "rock_benches", "freshwater_stream"]'::jsonb,
  'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '6 days',
  NOW()
),
(
  'spot-infanta-sand-dunes',
  'infanta-coastal-sand-dunes',
  'Infanta Coastal Sand Dunes & Beach',
  'Untouched expansive golden sand dunes and rolling coastal grasslands situated along the southernmost seaboard of Pangasinan facing Zambales and the open sea.',
  'nature_outdoors',
  'beach',
  '["sand_dunes", "beach", "coast", "scenic", "quiet"]'::jsonb,
  'Infanta',
  'Cato, Infanta, Pangasinan',
  15.8250,
  119.9083,
  0,
  '{"daily": "05:00-19:00"}'::jsonb,
  '["beach_access", "open_spaces", "coastal_trail", "sunset_view"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/places/infanta-beach/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '6 days',
  NOW()
),
(
  'spot-san-fabian-kite-beach',
  'san-fabian-kite-beach',
  'Kite Beach San Fabian',
  'The hub for windsurfing and kiteboarding enthusiasts in Northern Luzon, harnessing consistent onshore winds across the wide arc of Lingayen Gulf.',
  'activities_wellness',
  'water_activity',
  '["water_sports", "kiteboarding", "windsurfing", "beach", "adventure"]'::jsonb,
  'San Fabian',
  'Barangay Bolasi, San Fabian, Pangasinan',
  16.1415,
  120.4120,
  2,
  '{"daily": "08:00-18:00"}'::jsonb,
  '["gear_rental", "kite_instructor", "cottages", "parking", "restaurant"]'::jsonb,
  'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'medium',
  FALSE,
  NOW() - INTERVAL '5 days',
  NOW()
),
(
  'spot-mt-balungao-trail',
  'mount-balungao-summit-trail',
  'Mount Balungao Summit Trail & Zipline',
  'A scenic eco-adventure trail scaling the extinct volcano of Mount Balungao, offering a 600-meter extreme zipline descent and sweeping panoramic views across the central plains.',
  'activities_wellness',
  'recreation',
  '["hiking", "trail", "zipline", "panoramic_view", "adventure"]'::jsonb,
  'Balungao',
  'Mount Balungao Hill, Balungao, Pangasinan',
  15.8690,
  120.6890,
  2,
  '{"daily": "06:00-17:00"}'::jsonb,
  '["hiking_path", "zipline_station", "viewdeck", "restrooms", "guides"]'::jsonb,
  'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
  'lgu',
  'Balungao Tourism Office',
  'https://www.pangasinan.gov.ph/city-municipalities/balungao/',
  'lgu_verified',
  'published',
  'medium',
  FALSE,
  NOW() - INTERVAL '5 days',
  NOW()
),
(
  'spot-balincaguing-river',
  'balincaguing-river-eco-walk',
  'Balincaguing River Eco-Walk',
  'A peaceful freshwater riverside walk featuring bamboo suspension footbridges, native kayak tours, and shaded nipa sheds under mango trees in scenic Mabini.',
  'activities_wellness',
  'running_spot',
  '["walking", "river", "eco_trail", "kayaking", "family"]'::jsonb,
  'Mabini',
  'Poblacion Riverwalk, Mabini, Pangasinan',
  16.0712,
  119.9430,
  0,
  '{"daily": "05:00-19:00"}'::jsonb,
  '["walking_trail", "bamboo_bridges", "kayak_launch", "benches"]'::jsonb,
  'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '5 days',
  NOW()
),
(
  'spot-san-roque-dam-viewdeck',
  'san-roque-dam-reservoir-viewdeck',
  'San Roque Dam Reservoir & Viewdeck',
  'One of the largest multipurpose rock-fill embankment dams in Southeast Asia, providing majestic vantage points over emerald reservoir waters and the Cordillera mountain ranges.',
  'activities_wellness',
  'recreation',
  '["viewpoint", "mountains", "reservoir", "scenic", "engineering"]'::jsonb,
  'San Manuel',
  'San Roque, San Manuel, Pangasinan',
  16.1480,
  120.6850,
  0,
  '{"daily": "07:00-17:30"}'::jsonb,
  '["parking", "viewdeck", "security_post", "souvenirs", "photo_spot"]'::jsonb,
  'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Province of Pangasinan',
  'https://www.pangasinan.gov.ph/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '4 days',
  NOW()
),
(
  'spot-st-john-cathedral',
  'st-john-evangelist-cathedral-dagupan',
  'St. John the Evangelist Cathedral',
  'The historic metropolitan cathedral of the Archdiocese of Lingayen-Dagupan, rebuilt with grand neo-romanesque facades, stained glass vitrales, and solemn prayer chapels.',
  'culture_heritage',
  'church',
  '["cathedral", "church", "heritage", "architecture", "pilgrimage"]'::jsonb,
  'Dagupan City',
  'Burgos Street, Dagupan City, Pangasinan',
  16.0428,
  120.3345,
  0,
  '{"daily": "05:00-20:00"}'::jsonb,
  '["parking", "wheelchair_accessible", "prayer_garden", "parish_office"]'::jsonb,
  'https://images.unsplash.com/photo-1548625361-16a9a087192a?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Dagupan City Tourism',
  'https://dagupan.gov.ph/',
  'editorial',
  'published',
  'medium',
  FALSE,
  NOW() - INTERVAL '4 days',
  NOW()
),
(
  'spot-war-memorial-museum',
  'lingayen-gulf-war-memorial-museum',
  'Lingayen Gulf War Memorial Museum',
  'Historic beachfront military museum honoring General Douglas MacArthur''s Allied liberation forces in January 1945, displaying amphibious tanks, fighter aircraft, and historical war archives.',
  'culture_heritage',
  'museum',
  '["museum", "history", "wwii", "heritage", "education"]'::jsonb,
  'Lingayen',
  'Capitol Beachfront Complex, Lingayen, Pangasinan',
  16.0220,
  120.2325,
  0,
  '{"tuesday-sunday": "08:00-17:00"}'::jsonb,
  '["air_conditioned", "historical_artifacts", "tanks_display", "guided_tours", "wheelchair_accessible"]'::jsonb,
  'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
  'lgu',
  'Province of Pangasinan',
  'https://www.pangasinan.gov.ph/',
  'lgu_verified',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '4 days',
  NOW()
),
(
  'spot-binmaley-church',
  'binmaley-purification-parish-church',
  'Our Lady of the Purification Parish Church',
  'A towering 17th-century Spanish colonial Baroque church famous for its five-story octagonal bell tower, clay-brick buttresses, and proximity to Pangasinan''s coastal fishponds.',
  'culture_heritage',
  'church',
  '["church", "heritage", "baroque", "architecture", "belltower"]'::jsonb,
  'Binmaley',
  'Poblacion, Binmaley, Pangasinan',
  16.0306,
  120.2689,
  0,
  '{"daily": "06:00-18:30"}'::jsonb,
  '["parking", "wheelchair_accessible", "historical_marker", "plaza_access"]'::jsonb,
  'https://images.unsplash.com/photo-1548625361-16a9a087192a?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '3 days',
  NOW()
),
(
  'spot-limahong-channel',
  'limahong-channel-historical-marker',
  'Limahong Channel & Historical Marker',
  'The historic waterway along the Agno River mouth where Chinese corsair Limahong excavated his secret escape canal in 1574 to evade Spanish forces led by Juan de Salcedo.',
  'culture_heritage',
  'heritage_site',
  '["history", "heritage", "river", "monument", "education"]'::jsonb,
  'Lingayen',
  'Domalandan West, Lingayen, Pangasinan',
  16.0150,
  120.2180,
  0,
  '{"daily": "06:00-18:00"}'::jsonb,
  '["historical_marker", "viewing_deck", "river_walk", "photo_spot"]'::jsonb,
  'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
  'lgu',
  'Province of Pangasinan',
  'https://www.pangasinan.gov.ph/',
  'lgu_verified',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '3 days',
  NOW()
),
(
  'spot-lucap-wharf',
  'lucap-wharf-lighthouse-promenade',
  'Lucap Wharf & Lighthouse Promenade',
  'The lively seaside gateway to Hundred Islands National Park featuring a picturesque modern lighthouse, seaside food stalls, artisanal souvenir shops, and sunset benches.',
  'culture_heritage',
  'heritage_site',
  '["wharf", "lighthouse", "promenade", "food_stalls", "seaside"]'::jsonb,
  'Alaminos City',
  'Lucap, Alaminos City, Pangasinan',
  16.2085,
  119.9720,
  1,
  '{"daily": "05:00-22:00"}'::jsonb,
  '["parking", "boardwalk", "food_court", "boat_ticketing", "souvenirs", "lighting"]'::jsonb,
  'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80',
  'lgu',
  'Alaminos City Tourism',
  'https://www.alaminoscity.gov.ph/',
  'lgu_verified',
  'published',
  'high',
  FALSE,
  NOW() - INTERVAL '3 days',
  NOW()
),
(
  'spot-santo-domingo-church',
  'santo-domingo-heritage-church-san-manuel',
  'Santo Domingo Ybanag Heritage Church',
  'A picturesque century-old parish church standing in the foothills of San Manuel, celebrated for its antique wooden reredos, brick bell tower, and scenic mountain horizon.',
  'culture_heritage',
  'church',
  '["church", "heritage", "brick_architecture", "quiet", "pilgrimage"]'::jsonb,
  'San Manuel',
  'Poblacion, San Manuel, Pangasinan',
  16.0667,
  120.6667,
  0,
  '{"daily": "06:00-18:00"}'::jsonb,
  '["parking", "gardens", "benches", "historical_marker"]'::jsonb,
  'https://images.unsplash.com/photo-1548625361-16a9a087192a?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '3 days',
  NOW()
),
(
  'spot-san-carlos-mango-farms',
  'san-carlos-carabao-mango-agri-hub',
  'San Carlos Carabao Mango Agri-Hub',
  'The sweetest mango orchards of Pangasinan offering orchard farm tours, fresh carabao mango picking, dried mango candies, and artisanal mango puree tasting.',
  'eat_drink',
  'market',
  '["mango", "local_food", "agri_tourism", "fruit_farm", "pasalubong"]'::jsonb,
  'San Carlos City',
  'Barangay Magtaking, San Carlos City, Pangasinan',
  15.9281,
  120.3489,
  1,
  '{"daily": "07:00-18:00"}'::jsonb,
  '["parking", "farm_tours", "fruit_stalls", "mango_tasting", "restrooms"]'::jsonb,
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'San Carlos City Tourism',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'medium',
  FALSE,
  NOW() - INTERVAL '2 days',
  NOW()
),
(
  'spot-tayug-sunflower-maze',
  'tayug-sunflower-maze-agri-park',
  'Tayug Sunflower Maze & Agri-Park',
  'A famous flowering landscape labyrinth in Eastern Pangasinan featuring thousands of radiant giant sunflowers, marigold borders, melon tunnels, and farm-to-table snacks.',
  'nature_outdoors',
  'park',
  '["sunflower", "flowers", "photography", "maze", "family", "farm"]'::jsonb,
  'Tayug',
  'Barangay C. Lichauco, Tayug, Pangasinan',
  16.0300,
  120.7467,
  2,
  '{"daily": "07:00-17:30"}'::jsonb,
  '["parking", "flower_maze", "restrooms", "photo_stands", "fresh_produce"]'::jsonb,
  'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/places/tayug-sunflower-eco-park/',
  'editorial',
  'published',
  'high',
  FALSE,
  NOW() - INTERVAL '2 days',
  NOW()
),
(
  'spot-bani-watermelon-farms',
  'bani-watermelon-agri-tourism-farms',
  'Bani Watermelon & Agri-Tourism Farms',
  'The pakwan capital of Pangasinan showcasing rolling sand dunes planted with red and yellow sweet watermelons, hosting tasting harvest pavilions and juice kiosks.',
  'eat_drink',
  'market',
  '["watermelon", "local_produce", "farm", "sweet_fruits", "family"]'::jsonb,
  'Bani',
  'Barangay Poblacion, Bani, Pangasinan',
  16.1833,
  119.8667,
  1,
  '{"daily": "07:00-18:00"}'::jsonb,
  '["parking", "tasting_shed", "fresh_fruit_stalls", "farm_walk"]'::jsonb,
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
  'lgu',
  'Bani Tourism Office',
  'https://seepangasinan.com/',
  'lgu_verified',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '2 days',
  NOW()
),
(
  'spot-lingayen-bagoong-vats',
  'lingayen-artisanal-bagoong-factory',
  'Lingayen Artisanal Bagoong Factory',
  'Authentic fermenting vats of Pangasinan bagoong monamon and bagoong padas aging in antique earthen tapayan jars, producing the province''s world-renowned fish sauce.',
  'eat_drink',
  'local_food',
  '["bagoong", "culinary_heritage", "local_food", "pasalubong", "factory_tour"]'::jsonb,
  'Lingayen',
  'Barangay Maniboc, Lingayen, Pangasinan',
  16.0240,
  120.2290,
  1,
  '{"daily": "08:00-17:00"}'::jsonb,
  '["parking", "factory_view", "retail_store", "tasting_counter"]'::jsonb,
  'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Province of Pangasinan',
  'https://www.pangasinan.gov.ph/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '2 days',
  NOW()
),
(
  'spot-mangaldan-tupig',
  'mangaldan-tupig-carabao-dairy-center',
  'Mangaldan Tupig & Carabao Milk Center',
  'The culinary capital of grilled tupig—glutinous rice wrapped in banana leaves and roasted over coconut charcoal embers—paired with rich fresh carabao milk pastillas.',
  'eat_drink',
  'street_food',
  '["tupig", "street_food", "local_delicacy", "carabao_milk", "dessert"]'::jsonb,
  'Mangaldan',
  'Rizal Avenue, Mangaldan, Pangasinan',
  16.0711,
  120.4022,
  1,
  '{"daily": "06:00-21:00"}'::jsonb,
  '["parking", "street_stalls", "takeaway", "charcoal_grill_showcase"]'::jsonb,
  'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'high',
  FALSE,
  NOW() - INTERVAL '2 days',
  NOW()
),
(
  'spot-bonuan-blue-beach',
  'bonuan-blue-beach-seafood-shacks',
  'Bonuan Blue Beach Seafood Shacks',
  'The quintessential seafood dining strip in Dagupan City serving authentic boneless grilled bangus, buttered garlic prawns, and oyster kinilaw right along the coastline.',
  'eat_drink',
  'restaurant',
  '["bangus", "seafood", "dining", "beach_restaurant", "dagupan"]'::jsonb,
  'Dagupan City',
  'Bonuan Boquig, Dagupan City, Pangasinan',
  16.0820,
  120.3510,
  2,
  '{"daily": "10:00-22:00"}'::jsonb,
  '["parking", "seafood_display", "ocean_view_tables", "restrooms", "wifi"]'::jsonb,
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Dagupan City Tourism',
  'https://dagupan.gov.ph/',
  'editorial',
  'published',
  'high',
  FALSE,
  NOW() - INTERVAL '1 days',
  NOW()
),
(
  'spot-urdaneta-bagsakan',
  'urdaneta-city-wholesale-bagsakan-market',
  'Urdaneta City 24/7 Bagsakan Market',
  'The bustling trade gateway of Northern Luzon where farmers from across Pangasinan and the Cordilleras trade fresh vegetables, shallots, garlic braids, and local crops 24 hours a day.',
  'shopping_local',
  'market',
  '["market", "vegetables", "local_trade", "wholesale", "bustling"]'::jsonb,
  'Urdaneta City',
  'MacArthur Highway, Urdaneta City, Pangasinan',
  15.9758,
  120.5711,
  1,
  '{"daily": "24_hours"}'::jsonb,
  '["parking", "wholesale_sheds", "food_stalls", "loading_bays", "atm"]'::jsonb,
  'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Urdaneta City Tourism',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'high',
  FALSE,
  NOW() - INTERVAL '1 days',
  NOW()
),
(
  'spot-abundio-pottery',
  'san-nicolas-red-clay-pottery-center',
  'San Nicolas Red Clay Pottery Center',
  'An artisanal pottery colony hand-molding traditional terra-cotta clay stoves, plant pots, decorative urns, and culinary earthenware using ancient wood-burning pit kilns.',
  'shopping_local',
  'crafts',
  '["pottery", "handicrafts", "local_crafts", "terra_cotta", "souvenirs"]'::jsonb,
  'San Nicolas',
  'Barangay Sobol, San Nicolas, Pangasinan',
  16.0700,
  120.7633,
  1,
  '{"daily": "08:00-17:00"}'::jsonb,
  '["pottery_workshop", "hands_on_clay", "retail_sheds", "parking"]'::jsonb,
  'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Province of Pangasinan',
  'https://www.pangasinan.gov.ph/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '1 days',
  NOW()
),
(
  'spot-pozorrubio-blade-forge',
  'pozorrubio-master-cutlery-sword-forge',
  'Pozorrubio Master Cutlery & Sword Forge',
  'Heritage blacksmith forge famous for hand-hammering fine high-carbon steel blades, agricultural bolos, filipino martial arts training weapons, and chef knives.',
  'shopping_local',
  'crafts',
  '["blacksmith", "craftsmanship", "knives", "heritage_craft", "tools"]'::jsonb,
  'Pozorrubio',
  'Poblacion District, Pozorrubio, Pangasinan',
  16.1133,
  120.5467,
  2,
  '{"daily": "08:30-17:30"}'::jsonb,
  '["forge_viewing", "custom_blades", "knife_sharpening", "parking"]'::jsonb,
  'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '1 days',
  NOW()
),
(
  'spot-bayambang-bamboo-hub',
  'bayambang-st-vincent-bamboo-eco-park',
  'Bayambang St. Vincent & Bamboo Eco-Park',
  'Home of the Guinness World Record tallest bamboo sculpture of St. Vincent Ferrer (50.23m) surrounded by a relaxing bamboo garden park, prayer amphitheater, and reflection pools.',
  'activities_wellness',
  'park',
  '["bamboo_statue", "eco_park", "world_record", "pilgrimage", "scenic"]'::jsonb,
  'Bayambang',
  'Barangay Bani, Bayambang, Pangasinan',
  15.8117,
  120.4561,
  0,
  '{"daily": "06:00-20:00"}'::jsonb,
  '["parking", "viewing_amphitheater", "gardens", "restrooms", "souvenir_stalls"]'::jsonb,
  'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1200&q=80',
  'lgu',
  'Bayambang Tourism Office',
  'https://seepangasinan.com/places/st-vincent-ferrer-statue/',
  'lgu_verified',
  'published',
  'medium',
  FALSE,
  NOW() - INTERVAL '1 days',
  NOW()
),
(
  'spot-umingan-highland-ridge',
  'umingan-highland-viewdeck-pine-ridge',
  'Umingan Highland Viewdeck & Pine Ridge',
  'A refreshing elevated mountain ridge vantage point along the foothills of Eastern Pangasinan offering pine tree breezes, sunrise sea-of-clouds vistas, and cool mountain retreats.',
  'nature_outdoors',
  'viewpoint',
  '["mountains", "viewpoint", "pine_trees", "sea_of_clouds", "cool_weather"]'::jsonb,
  'Umingan',
  'Barangay Flores, Umingan, Pangasinan',
  15.9267,
  120.8400,
  0,
  '{"daily": "05:00-18:30"}'::jsonb,
  '["viewdeck", "benches", "camp_sites", "coffee_shed", "parking"]'::jsonb,
  'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '12 hours',
  NOW()
),
(
  'spot-sual-sunset-lookout',
  'sual-power-vista-sunset-lookout',
  'Sual Power Vista & Sunset Lookout',
  'A hilltop overlook commanding panoramic vistas of Sual deep-water harbor, coastal coves, anchored cargo ships, and the golden dusk twilight reflecting off the gulf.',
  'nature_outdoors',
  'viewpoint',
  '["viewdeck", "harbor", "sunset", "scenic", "panoramic_view"]'::jsonb,
  'Sual',
  'Barangay Pangascasan, Sual, Pangasinan',
  16.0633,
  120.0933,
  0,
  '{"daily": "06:00-19:00"}'::jsonb,
  '["viewpoint_pavilion", "parking", "photo_deck", "benches"]'::jsonb,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '8 hours',
  NOW()
),
(
  'spot-mangatarem-citrus-trail',
  'mangatarem-calamansi-citrus-orchard',
  'Mangatarem Calamansi & Citrus Orchard',
  'An agri-tourism orchard nestled along the base of the Zambales Mountains growing fragrant calamansi, dalandan oranges, and pomelos with farm picking and fresh juice bars.',
  'eat_drink',
  'market',
  '["citrus", "orchard", "fruit_farm", "local_produce", "nature"]'::jsonb,
  'Mangatarem',
  'Barangay Pacalat, Mangatarem, Pangasinan',
  15.7897,
  120.2947,
  1,
  '{"daily": "07:30-17:00"}'::jsonb,
  '["orchard_walk", "fruit_tasting", "farm_store", "parking", "restrooms"]'::jsonb,
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Province of Pangasinan',
  'https://www.pangasinan.gov.ph/',
  'editorial',
  'published',
  'low',
  FALSE,
  NOW() - INTERVAL '6 hours',
  NOW()
),
(
  'spot-rosales-heritage-station',
  'rosales-heritage-train-depot-eco-park',
  'Rosales Heritage Train Depot & Eco-Park',
  'A restored early-20th-century Manila-Dagupan railway depot showcasing historical locomotives, shaded acacia tree avenues, community bike paths, and street food kiosks.',
  'culture_heritage',
  'heritage_site',
  '["railway", "history", "heritage", "train_station", "park"]'::jsonb,
  'Rosales',
  'Poblacion, Rosales, Pangasinan',
  15.8942,
  120.6339,
  0,
  '{"daily": "06:00-21:00"}'::jsonb,
  '["historic_locomotive", "bike_paths", "benches", "food_stalls", "parking"]'::jsonb,
  'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
  'editorial',
  'Pangasinan PTCAO',
  'https://seepangasinan.com/',
  'editorial',
  'published',
  'medium',
  FALSE,
  NOW() - INTERVAL '4 hours',
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  tags = EXCLUDED.tags,
  municipality = EXCLUDED.municipality,
  address = EXCLUDED.address,
  gps_lat = EXCLUDED.gps_lat,
  gps_lng = EXCLUDED.gps_lng,
  price_level = EXCLUDED.price_level,
  hours = EXCLUDED.hours,
  amenities = EXCLUDED.amenities,
  image_url = EXCLUDED.image_url,
  source_type = EXCLUDED.source_type,
  source_name = EXCLUDED.source_name,
  source_url = EXCLUDED.source_url,
  trust_level = EXCLUDED.trust_level,
  status = EXCLUDED.status,
  crowd_capacity_band = EXCLUDED.crowd_capacity_band,
  is_test = EXCLUDED.is_test,
  updated_at = NOW();
